sys_arch: Fix compile error on gcc 4.7
gcc noticed that the sys_mbox_valid() macro always evaluates to true,
because &foo can't be a NULL pointer:

    ../../../../../lwip/src/api/tcpip.c: In function `tcpip_input':
    lwip/src/api/tcpip.c:176:7: error: the comparison will always evaluate as `true' for the address of `mbox' will never be NULL [-Werror=address]

Replace it with a (maybe non-portable) inline function.

Signed-off-by: Kevin Cernekee <cernekee@gmail.com>